In [1]:
import pickle
dir = "/eos/user/g/gkrzmanc/2024/cluster_features_filt_2305_correct_thetaphi/cluster_features_filt/c9kmgl3r9s.pkl"
with open(dir, 'rb') as f:
    data = pickle.load(f)
    

In [36]:
data["pid_y"][8]

211.0

In [37]:
data["x"]
coords = data["x"][:, [9, 10, 11]]

In [38]:
coords[8]

tensor([ 0.1412, -0.7180,  0.0442])

In [39]:
import torch
# normalize
coords[8] / torch.norm(coords[8])

tensor([ 0.1927, -0.9794,  0.0602])

In [40]:
import numpy as np
data["coords_y"][8] / np.linalg.norm(data["coords_y"][8])

array([ 0.647511  , -0.7590584 ,  0.06752625], dtype=float32)